---
- name: Disable SELinux and Firewalld
  hosts: all
  become: true

  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Stop and disable Firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
