---
- name: Configure Nginx as a reverse proxy
  hosts: all
  become: true

  tasks:
    - name: Configure Nginx reverse proxy
      template:
        src: nginx_proxy.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
     
    - name: Restart Nginx service
      systemd:
        name: nginx
        state: restarted